site_name: My Docs
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
theme:
      name: material
      palette : 
        scheme : slate
        primary : red   
